tap "caskroom/cask"
tap "caskroom/versions"
tap "ethereum/ethereum"
tap "homebrew/bundle"
tap "homebrew/core"
tap "railwaycat/emacsmacport"
tap "paritytech/paritytech"
cask "java"
brew "amazon-ecs-cli"
brew "aspell"
brew "autoconf"
brew "automake"
brew "awscli"
brew "openssl"
brew "axel"
brew "berkeley-db@4"
brew "boost", args: ["c++11"]
brew "coreutils"
brew "cputhrottle"
brew "ctags"
brew "curl"
brew "cloc"
brew "ec2-api-tools"
brew "exa"
brew "fish"
brew "git"
brew "gnupg"
brew "graphviz"
brew "libtool"
brew "imagemagick"
brew "jq"
brew "jsonpp"
brew "libevent"
brew "libgit2"
brew "libxslt"
brew "readline"
brew "macvim"
brew "mas"
brew "miniupnpc"
brew "nload"
brew "parity"
brew "peco"
brew "pkg-config"
brew "postgresql"
brew "protobuf"
brew "qt"
brew "reattach-to-user-namespace"
brew "roundup"
brew "sbt"
brew "scala"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "unixodbc"
brew "wget"
brew "wxmac"
brew "yarn", args: ["without-node"]
brew "ethereum/ethereum/ethereum"
brew "ethereum/ethereum/solidity"
cask "alfred2"
cask "appcleaner"
cask "bartender"
cask "brave"
cask "charles"
cask "colloquy"
cask "dash"
cask "disk-inventory-x"
cask "docker"
cask "duet"
cask "kitematic"
cask "dropbox"
cask "emacs-mac"
cask "evernote"
cask "filezilla"
cask "firefox"
cask "flash-npapi"
cask "flash-player"
cask "franz"
cask "github-desktop"
cask "google-chrome"
cask "gfxcardstatus"
cask "haskell-platform"
cask "hex-fiend"
cask "istat-menus"
cask "iterm2"
cask "keka"
cask "kindle"
cask "ksdiff"
cask "lastpass"
cask "macvim"
cask "music-manager"
cask "osxfuse"
cask "parallels-desktop"
cask "pgadmin4"
cask "postico"
cask "radiant-player"
cask "rubymine"
cask "sizeup"
cask "skitch"
cask "slack"
cask "sourcetree"
cask "skype"
cask "teamviewer"
cask "telegram"
cask "transmission"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
mas "ForkLift", id: 412448059
mas "GIPHY CAPTURE", id: 668208984
mas "Growl", id: 467939042
mas "KakaoTalk", id: 869223134
mas "Kaleidoscope", id: 587512244
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "Microsoft Remote Desktop", id: 715768417
mas "Movist", id: 461788075
mas "OmniGraffle", id: 711830901
mas "Pages", id: 409201541
mas "PhotoScapeX", id: 929507092
mas "PopupDic", id: 765419220
mas "Xcode", id: 497799835
